### ISSUE TITLE
Online data pull

### ISSUE THREAD

**Issue by mahmoodabed** [ja33man/apnea#1]
Hi

Thank you for this great repository.

I have this issue here kindly can you see it?

TypeError                                 Traceback (most recent call last)
<ipython-input-22-baf3b2b83e32> in <module>()
----> 1 labels = wfdb.rdann(os.path.split(dfCatalog['Folder'].iloc[patientID])[0],pb_dir='{0}/{1}/'.format(challenge_name ,os.path.split(dfCatalog['Folder'].iloc[patientID])[0]), extension='arousal')
      2 
      3 # Getting signals
      4 # Should be used when signals pulled from the web
      5 signals, fields = wfdb.rdsamp(os.path.split(dfCatalog['Folder'].iloc[patientID])[0],pb_dir='{0}/{1}/'.format(challenge_name ,os.path.split(dfCatalog['Folder'].iloc[patientID])[0]), channels=channels)

TypeError: rdann() got an unexpected keyword argument 'pb_dir'

**Comment by mahmoodabed** [comment]
wfdb       1.3.7
numpy      1.16.4
IPython    5.5.0
matplotlib 3.0.3
pandas     0.24.2

**Comment by jazzman37** [comment]
Can you please confirm that you are using `wfdb` version  `2.0.2`

**Comment by ja33man** [comment]
Please check your `wfdb` version, it should be above `2.0.2`.

The following code works in both `2.0.2` and `2.2.1`:
labels = wfdb.rdann(record_name='tr03-0005', pb_dir='challenge/2018/training//tr03-0005/', extension='arousal')  

If you have an earlier version of `wfdb` try replacing `pb_dir` with `pbdir`

**Comment by mahmoodabed** [comment]
It's working now thanks, I had to upgrade it to 2.0.2.
Before I close the issue please sir may I know whether you downloaded the whole dataset files (training and testing) which is about 270 GB because I am planning to use Colab, is there any method to pull the dataset over GOOGLE CLOUD.

**Comment by ja33man** [comment]
To pull dataset from physionet you can use torrent (https://physionet.org/content/challenge-2018/1.0.0/):
`https://physionet.org/challenge/2018/training.torrent`
or the following terminal command:
`wget  -r -np -nH --cut-dirs=4 -R "index.html*" -e robots=off  "https://physionet.org/physiobank/database/challenge/2018/training/"`

Please keep in mind that the `test` dataset doesn't contain arousal labels, so you can only use it for unsupervised learning.
